### ISSUE TITLE
Unable to intercept MSEdge.exe launched via sihost.exe

### ISSUE THREAD

**Issue by Yannik** [rcmaehl/MSEdgeRedirect#143]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Open link in the windows settings

Example links where this occurs:

![Screenshot from 2022-06-05 01-15-56](https://user-images.githubusercontent.com/801996/172028462-0dd65e68-c830-42dd-a3ce-a12e2fdf0a28.png)

### ✔️ Expected Behavior

Links should open in Firefox

### ❌ Actual Behavior

Edge is opened, but the link is not opened (the tab says "crashed")

### Microsoft Windows version

Windows 11 21H2 build 22000.708

**Comment by rcmaehl** [comment]
I'll take a look. Thanks!

**Comment by gnpaone** [comment]
I have a different experience with this same issue
Previous version (last updated 2-3 weeks back - nightly version) gave this error:
![image](https://user-images.githubusercontent.com/78990165/172154816-aed5e0fe-bde9-42fd-be27-e92b1c16e0fd.png)
Latest nightly version opens the sedge browser with that white screen as seen in the screenshot (no error) and the edge closes immediately after a second

**Comment by trallnag** [comment]
- EdgeRedirect: 0.7.0.1
- Edge: 104.0.1293.47

![Animation](https://user-images.githubusercontent.com/24834206/184201738-3bd91ef9-c2ce-4cea-b174-219ce07e8ddf.gif)

Interestingly if I open Edge and then click on the Help link in the settings app Edge goes into focus and a new tab opens to a bing search.

    https://www.bing.com/search?q=change%20taskbar%20color%20windows%2011%20site:microsoft.com&form=B00032&ocid=SettingsHAQ-BingIA&mkt=en-US

**Comment by rcmaehl** [comment]
> * EdgeRedirect: 0.7.0.1
> * Edge: 104.0.1293.47
> 
> ![Animation](https://user-images.githubusercontent.com/24834206/184201738-3bd91ef9-c2ce-4cea-b174-219ce07e8ddf.gif) [ ![Animation](https://user-images.githubusercontent.com/24834206/184201738-3bd91ef9-c2ce-4cea-b174-219ce07e8ddf.gif) ](https://user-images.githubusercontent.com/24834206/184201738-3bd91ef9-c2ce-4cea-b174-219ce07e8ddf.gif) [ ](https://user-images.githubusercontent.com/24834206/184201738-3bd91ef9-c2ce-4cea-b174-219ce07e8ddf.gif)
> 
> Interestingly if I open Edge and then click on the Help link in the settings app Edge goes into focus and a new tab opens to a bing search.
> 
> ```
> https://www.bing.com/search?q=change%20taskbar%20color%20windows%2011%20site:microsoft.com&form=B00032&ocid=SettingsHAQ-BingIA&mkt=en-US
> ```

This looks like you're running Service Mode. Is that right? If possible, can you upload `%localappdata%\MSEdgeRedirect\Logs`

**Comment by trallnag** [comment]
@rcmaehl, here you go. I deleted all logs and then clicked again on the link / button that is failing.

[logs.zip](https://github.com/rcmaehl/MSEdgeRedirect/files/9311148/logs.zip)

URIFailures.log

```txt
2022/08/11 20:19:26 - Invalid URL: --type=crashpad-handler --user-data-dir=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data\Crashpad --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.47 --initial-client-data=0x130,0x134,0x138,0x10c,0x140,0x7ffc8e8d8250,0x7ffc8e8d8260,0x7ffc8e8d8270
2022/08/11 20:19:26 - Invalid URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=2100 --field-trial-handle=2200,i,2577272280514638276,4106256247201887788,131072 /prefetch:3
2022/08/11 20:19:26 - Invalid URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=3852 --field-trial-handle=2200,i,2577272280514638276,4106256247201887788,131072 /prefetch:3
```

AppSecurity.log

```txt
2022/08/11 20:19:26 - Blocked Unsafe URL: --type=crashpad-handler --user-data-dir=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data\Crashpad --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.47 --initial-client-data=0x130,0x134,0x138,0x10c,0x140,0x7ffc8e8d8250,0x7ffc8e8d8260,0x7ffc8e8d8270
2022/08/11 20:19:26 - Blocked Unsafe URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=2100 --field-trial-handle=2200,i,2577272280514638276,4106256247201887788,131072 /prefetch:3
2022/08/11 20:19:26 - Blocked Unsafe URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=3852 --field-trial-handle=2200,i,2577272280514638276,4106256247201887788,131072 /prefetch:3
```

**Comment by trallnag** [comment]
And here again, but with Edge open in the background.

[logs.zip](https://github.com/rcmaehl/MSEdgeRedirect/files/9311173/logs.zip)

URIFailures.log

```txt
2022/08/11 20:23:35 - Invalid URL: --type=crashpad-handler --user-data-dir=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data\Crashpad --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.47 --initial-client-data=0x130,0x134,0x138,0x10c,0x140,0x7ffc8e8d8250,0x7ffc8e8d8260,0x7ffc8e8d8270
```

AppSecurity.log

```txt
2022/08/11 20:23:35 - Blocked Unsafe URL: --type=crashpad-handler --user-data-dir=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\timsc\AppData\Local\Microsoft\Edge\User Data\Crashpad --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.47 --initial-client-data=0x130,0x134,0x138,0x10c,0x140,0x7ffc8e8d8250,0x7ffc8e8d8260,0x7ffc8e8d8270
```

**Comment by Mipsters** [comment]
good catch guys!
was about to report the same thing :)

found more links in windows insider menus
Settings > Windows Update > Windows Insider Program
under "Related support", click on "Becoming a Windows Insider" or "Leave the insider program"

"Becoming a Windows Insider" links to
"https://insider.windows.com/getting-started"
(redirects to https://insider.windows.com/<language-code\>/getting-started)

"Leave the insider program" links to
"https://insider.windows.com/leave-program"
(redirects to https://insider.windows.com/<language-code\>/leave-program)

Windows: 22H2 build 22622.575


### edge closed

AppSecurity.log:
```
2022/08/13 13:00:45 - Blocked Unsafe URL: --type=crashpad-handler --user-data-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data\Crashpad --metrics-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.54 --initial-client-data=0x114,0x118,0x11c,0xf0,0x124,0x7ffe15fc8250,0x7ffe15fc8260,0x7ffe15fc8270
2022/08/13 13:00:45 - Blocked Unsafe URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=2352 --field-trial-handle=2004,i,10614741675680621460,6631899872687424811,131072 /prefetch:3
2022/08/13 13:00:46 - Blocked Unsafe URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=3932 --field-trial-handle=2004,i,10614741675680621460,6631899872687424811,131072 /prefetch:3
```
URIFailures.log:
```
2022/08/13 13:00:45 - Invalid URL: --type=crashpad-handler --user-data-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data\Crashpad --metrics-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.54 --initial-client-data=0x114,0x118,0x11c,0xf0,0x124,0x7ffe15fc8250,0x7ffe15fc8260,0x7ffe15fc8270
2022/08/13 13:00:45 - Invalid URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=2352 --field-trial-handle=2004,i,10614741675680621460,6631899872687424811,131072 /prefetch:3
2022/08/13 13:00:46 - Invalid URL: --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --mojo-platform-channel-handle=3932 --field-trial-handle=2004,i,10614741675680621460,6631899872687424811,131072 /prefetch:3
```

### edge open

AppSecurity.log:
```
2022/08/13 13:09:07 - Blocked Unsafe URL: --type=crashpad-handler --user-data-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data\Crashpad --metrics-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.54 --initial-client-data=0x128,0x12c,0x130,0x104,0x138,0x7ffe3cd48250,0x7ffe3cd48260,0x7ffe3cd48270
```
URIFailures.log:
```
2022/08/13 13:09:07 - Invalid URL: --type=crashpad-handler --user-data-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data /prefetch:7 --monitor-self-annotation=ptype=crashpad-handler --database=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data\Crashpad --metrics-dir=C:\Users\<Username>\AppData\Local\Microsoft\Edge\User Data --annotation=IsOfficialBuild=1 --annotation=channel= --annotation=chromium-version=104.0.5112.81 --annotation=exe=C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --annotation=plat=Win64 --annotation=prod=Microsoft Edge --annotation=ver=104.0.1293.54 --initial-client-data=0x128,0x12c,0x130,0x104,0x138,0x7ffe3cd48250,0x7ffe3cd48260,0x7ffe3cd48270
```

**Comment by Mipsters** [comment]
I looked at it abit
seems like Windows Settings runs the following command
```
"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --single-argument microsoft-edge:https://insider.windows.com/getting-started
```
I checked @trallnag example, its the same form with a different url after "microsoft-edge:"

**Comment by rcmaehl** [comment]
Hi all this should be fixed. If not, please let me know!

**Comment by Yannik** [comment]
Hi @rcmaeh

Great!

Could you point me to the change which fixes this issue?

**Comment by Yannik** [comment]
Hi @rcmaehl

Great!

Could you point me to the change which fixes this issue?

**Comment by Yannik** [comment]
@rcmaehl Atleast with  release 0.7.2.0 this does not seem to be fixed. Links from the settings page are opening in edge.

**Comment by Yannik** [comment]
I have built the latest master branch myself ([64b685b](https://github.com/rcmaehl/MSEdgeRedirect/commit/64b685b03484b0d134246d28f814281013eb8392)), the issue still persists.

**Comment by rcmaehl** [comment]
> I have built the latest master branch ([64b685b](https://github.com/rcmaehl/MSEdgeRedirect/commit/64b685b03484b0d134246d28f814281013eb8392)) myself, the issue still persists.

Is it those two links still. I've been unable to reproduce on my end:

![cantrepo](https://user-images.githubusercontent.com/716581/205536482-61872c2b-a43b-4e8a-9217-1465b5a156c8.gif)

If you haven't already, please run the Cleanup tool and then reinstall:

https://raw.githubusercontent.com/rcmaehl/MSEdgeRedirect/main/Assets/Cleanup%20Tool.ps1

**Comment by Yannik** [comment]
@rcmaehl please check the links in the OP:
https://user-images.githubusercontent.com/801996/172028462-0dd65e68-c830-42dd-a3ce-a12e2fdf0a28.png

These are the ones I was testing

**Comment by Yannik** [comment]
@rcmaehl I have run Cleanup Tool and then reinstalled the latest master, the issue still persists with the links Settings -> Privacy and Security -> Managing Account Privacy settings / Change Account Privacy settings

**Comment by Remzi1993** [comment]
> ### Preflight Checklist
> * [x]  Microsoft Edge is still installed (see issue 26)
> * [x]  Running microsoft-edge:https://google.com redirects successfully
> * [ ]  Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)
> 
> ### Install Type
> New Install
> 
> ### Install Mode
> Active Mode
> 
> ### Steps to reproduce
> Open link in the windows settings
> 
> Example links where this occurs:
> 
> ![Screenshot from 2022-06-05 01-15-56](https://user-images.githubusercontent.com/801996/172028462-0dd65e68-c830-42dd-a3ce-a12e2fdf0a28.png)
> 
> ### ✔️ Expected Behavior
> Links should open in Firefox
> 
> ### ❌ Actual Behavior
> Edge is opened, but the link is not opened (the tab says "crashed")
> 
> ### Microsoft Windows version
> Windows 11 21H2 build 22000.708
> 
> ### Other Software
> _No response_

I have the exact same behaviour after installing redirect. I hope this gets fixed. I'm on the latest stable build of Windows 11, build: 22621.963

**Comment by rch77** [comment]
I have the same issue with 0.7.3.0 Active Mode, Firefox as default browser, Windows Home 11 10.22621. Trying to open any link in Settings like "Getting new wallpapers every day from Microsoft" without Edge window currently open results in blank window flashing for a second and disappearing. It doesn't crash but opens new tab if Edge is already opened.
Crash event ID 1000 in Event Log:
```
Faulting application name: msedge.exe, version: 111.0.1661.54, time stamp: 0x641d5ed2
Faulting module name: msedge.dll, version: 111.0.1661.54, time stamp: 0x641d5ed2
Exception code: 0x80000003
Fault offset: 0x0000000002093a2d
Faulting process id: 0x0x3F40
Faulting application start time: 0x0x1D96458A05ABD69
Faulting application path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
Faulting module path: C:\Program Files (x86)\Microsoft\Edge\Application\111.0.1661.54\msedge.dll
Report Id: c8d81d61-e5a9-4f19-9f4d-f8ec6522a85f
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by Yannik** [comment]
@rcmaehl Do you an idea how to fix this?

**Comment by rcmaehl** [comment]
There's been some changes on IFEO handling for the upcoming release. If you're having the issue, can you test out the dev build and let me know if it's improved at all?

https://github.com/rcmaehl/MSEdgeRedirect/suites/11747883615/artifacts/612058373

**Comment by rch77** [comment]
It looks the same.
Faulting application name: msedge.exe, version: 111.0.1661.62, time stamp:
0x6424ce40
Faulting module name: msedge.dll, version: 111.0.1661.62, time stamp:
0x6424ce40
Exception code: 0x80000003
Fault offset: 0x00000000020b3f3d
Faulting process id: 0x0x3D94
Faulting application start time: 0x0x1D96656F0130C3E
Faulting application path: C:\Program Files
(x86)\Microsoft\Edge\Application\msedge.exe
Faulting module path: C:\Program Files
(x86)\Microsoft\Edge\Application\111.0.1661.62\msedge.dll
Report Id: 8e36e487-b4b6-4475-92ee-2511130c4948
Faulting package full name:
Faulting package-relative application ID:

**Comment by rcmaehl** [comment]
Was able to reproduce. Working on it

**Comment by rcmaehl** [comment]
Interestingly enough... MSEdgeRedirect is being launched... just somehow being killed.

![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/5f6c1e01-e1f1-4f05-9547-8dd545b5a54b)

**Comment by rcmaehl** [comment]
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/716581/8b454de4-4917-4943-9896-d46aa207c7a2)

So it appears in certain situations sihost is directly launching edge. 

I might be able to work around this...

**Comment by HarshalKudale** [comment]
Is MSedgeRedirect recieving the arguments in case of failure? I tried replacing MSedgeRedirect with a cpp program that just shows args passed to it. If what you saying is the case app will not recieve the args so settings links will only work in service mode

**Comment by rcmaehl** [comment]
In this specific case, the msedge.exe launched by sihost.exe has already "consumed" the arguments we need. We have enough time to recover them however.

**Comment by rcmaehl** [comment]
BINGO 👏

**Comment by Yannik** [comment]
@rcmaehl that's great! Does this fix work for both active and service mode?

**Comment by Yannik** [comment]
@rcmaehl one more thing... I tried to test this using the "download testing" link on the main repo page, but that seems to be broken.

**Comment by rcmaehl** [comment]
> @rcmaehl that's great! Does this fix work for both active and service mode?

It _should_

**Comment by rcmaehl** [comment]
> @rcmaehl one more thing... I tried to test this using the "download testing" link on the main repo page, but that seems to be broken.

The download itself, or installing the version from the download. If referring to the download itself, I'm aware... it seems to be in limbo of working and not working due to smartscreen / safe browsing.

**Comment by Yannik** [comment]
The download. Now it's working though.

**Comment by Yannik** [comment]
@rcmaehl Your patch does fix things, however, there are two caveats:
* there is a brief flash of an edge window 
* sometimes (couldn't reliably reproduce this) two tabs are opened for clicking a link once

If I understood your explanations correctly, it seems like the first call to msedge.exe is evading the IFEO debugger, correct? 
Would it not be the nicer solution to fix this, instead of using this workaround?

**Comment by rcmaehl** [comment]
> @rcmaehl Your patch does fix things, however, there are two caveats:
> 
> * there is a brief flash of an edge window
> * sometimes (couldn't reliably reproduce this) two tabs are opened for clicking a link once
> 
> If I understood your explanations correctly, it seems like the first call to msedge.exe is evading the IFEO debugger, correct? Would it not be the nicer solution to fix this, instead of using this workaround?

Yes. I'm still investigating why the first call isn't using the IFEO debugger, but this workaround re-enables the broken functionality until I figure out a fix to the avoidance (if possible)

**Comment by Yannik** [comment]
Hi Robert,

makes sense to me. Should I open a separate new issue for this?

I had one more look at the IFEO config:
Could the IFEO debugger not being triggered possibly be caused by the `FilterFullPath` option?

**Comment by rcmaehl** [comment]
> Hi Robert,
> 
> makes sense to me. Should I open a separate new issue for this?
> 
> I had one more look at the IFEO config: Could the IFEO debugger not being triggered possibly be caused by the `FilterFullPath` option?

Shouldn't be.
