### ISSUE TITLE
MSEDGE_NO_IFEO.exe Errors

### ISSUE THREAD

**Issue by rcmaehl** [rcmaehl/MSEdgeRedirect#25]
## How to fix:

A temporary fix has been added. If you receive this error, run `MSEdgeRedirect.exe /repair` from an admin command prompt.

&nbsp;
&nbsp;
&nbsp;

## Original bug report

![image](https://user-images.githubusercontent.com/69052158/144716867-77f2c31d-c4f4-4d35-b9c5-75a3b1e7b295.png)

Don't know why but edge stopped opening again, tried reinstaling msedgeredirect, but that didn't fix it.

_Originally posted by @0ibaba in https://github.com/rcmaehl/MSEdgeRedirect/issues/15#issuecomment-986053730_

**Comment by 0ibaba** [comment]
@rcmaehl 
![Screenshot 2021-12-05 062920](https://user-images.githubusercontent.com/69052158/144729320-115c23fd-a25c-4f1a-a64b-4ca180534ce4.png)

I'm on Window 11 build 22000.348

**Comment by rcmaehl** [comment]
> @rcmaehl
> 
> I'm on Window 11 build 22000.348

I @0ibaba try running the following commands in an admin CMD:

`C:\Program Files (x86)\Microsoft\Edge\Application`
`copy /Y msedge.exe msedge_no_ifeo.exe`

![image](https://user-images.githubusercontent.com/716581/144758932-936bceba-8a7b-45a2-8166-d01d84218315.png)

**Comment by 0ibaba** [comment]
@rcmaehl Sorry for the late reply, it does seem to fix the problem

**Comment by pratyakshm** [comment]
> @rcmaehl Sorry for the late reply, it does seem to fix the problem
> 
> Edit: I uninstalled msedgeredirect and deleted msedge_no_ifeo.exe, and it works just fine. msedge_no_ifeo.exe only gets created after installing msedgeredirect, I don't know if this is something that's needed for it to work.

Can you please explain how did you uninstall MSER?
In the readme, it says to simply delete the EXE - but I do not understand where else to delete the EXE from except my Downloads folder. I am asking because I want to re-install MSER from scratch with different configuration options.

**Comment by 0ibaba** [comment]
@pratyakshm So there should be an exe file in programfiles or C:\Users\*user*\AppData\Local\MSEdgeRedirect depending on if you used the active mode or service mode. But deleting them won't completely remove it.

There might be better ways, but I'm using revo uninstaller

**Comment by rcmaehl** [comment]
> > @rcmaehl Sorry for the late reply, it does seem to fix the problem
> > Edit: I uninstalled msedgeredirect and deleted msedge_no_ifeo.exe, and it works just fine. msedge_no_ifeo.exe only gets created after installing msedgeredirect, I don't know if this is something that's needed for it to work.
> 
> Can you please explain how did you uninstall MSER? In the readme, it says to simply delete the EXE - but I do not understand where else to delete the EXE from except my Downloads folder. I am asking because I want to re-install MSER from scratch with different configuration options.

I need to update that. With 0.4.0.0 you can uninstall from programs and features

**Comment by rcmaehl** [comment]
A temporary fix has been added. If you receive this error, run `MSEdgeRedirect.exe /repair` from an admin command prompt.

**Comment by 0ibaba** [comment]
Hi, so I'm not sure why, but this has been happening again lately. Running the setup again fixes it, but it keeps happening every few days.
Currently, I have "msedge_no_ifeo.exe" set to open PDFs, and I'm not sure if this is causing it.
I'm on the latest version

**Comment by rcmaehl** [comment]
> Hi, so I'm not sure why, but this has been happening again lately. Running the setup again fixes it, but it keeps happening every few days. Currently, I have "msedge_no_ifeo.exe" set to open PDFs, and I'm not sure if this is causing it. I'm on the latest version

Try the latest dev build. There was some minor issues that are fixed

**Comment by 0ibaba** [comment]
> Try the latest dev build. There was some minor issues that are fixed

So I installed the dev build, and it still broke. I'm not sure if it's something I'm doing

**Comment by rcmaehl** [comment]
> > Try the latest dev build. There was some minor issues that are fixed
> 
> So I installed the dev build, and today it broke again. I'm not sure if it's something I'm doing

Try deselecting "PDF Handler" in settings.

**Comment by 0ibaba** [comment]
> Try deselecting "PDF Handler" in settings.

I'll try that and see if it happens again

**Comment by 0ibaba** [comment]
@rcmaehl Still getting that. I don't usually use edge, so I can't really say how long it took for it to stop working again.

**Comment by rcmaehl** [comment]
> @rcmaehl Still getting that. I don't usually use edge, so I can't really say how long it took for it to stop working again.

Please try the latest dev build if you aren't already.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by 0ibaba** [comment]
@rcmaehl So I was using the one you linked for a few days and looks like it's working fine. Should I try with pdf handler enabled?

**Comment by rcmaehl** [comment]
> @rcmaehl So I was using the one you linked for a few days and looks like it's working fine. Should I try with pdf handler enabled?

Feel free to do so.

**Comment by 0ibaba** [comment]
> Feel free to do so.

Looks like it's fixed :)
