### ISSUE TITLE
Uninstalling MSEdgeRedirect deletes Microsoft Edge exe

### ISSUE THREAD

**Issue by SeriousHoax** [rcmaehl/MSEdgeRedirect#267]
### Preflight Checklist

- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box

### Install Type

New Install

### Install Mode

Active Mode

### Steps to reproduce

Uninstall MSEdgeRedirect

### ✔️ Expected Behavior

Edge should run just fine after uninstalling MSEdgeRedirect

### ❌ Actual Behavior

Doesn't run, exe missing:
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/29574622/116d1949-8568-42fc-94f9-e294ae3f1d6f)
![image](https://github.com/rcmaehl/MSEdgeRedirect/assets/29574622/1ac7897f-f98c-4356-8e47-9214cd5fdcd2)

### Microsoft Windows version

Windows 11 22H2

### Other Software

Nothing noteworthy

**Comment by rcmaehl** [comment]
Should be fixed in the latest dev build

**Comment by SeriousHoax** [comment]
> Should be fixed in the latest dev build

Thanks. The issue is quite serious but harmless as long as a user doesn't uninstall it. Push the fix to the stable build quickly if possible.

**Comment by sdellysse** [comment]
So I just got bit by this bug this morning, as far as I can tell I was on the latest build available via scoop. Now I'm running the Edge repair/uninstaller to see if it can fix that

**Comment by SeriousHoax** [comment]
> So I just got bit by this bug this morning, as far as I can tell I was on the latest build available via scoop. Now I'm running the Edge repair/uninstaller to see if it can fix that

Just download and install the offline installer from here and everything will be normal again: 
https://www.microsoft.com/en-us/edge/business/download

**Comment by Remzi1993** [comment]
@rcmaehl I just uninstalled this app and this is still happening.

**Comment by rcmaehl** [comment]
> @rcmaehl I just uninstalled this app and this is still happening.

Morning, this is fixed in the dev build.
