### ISSUE TITLE
msedge_elf.dll missing in Active Mode

### ISSUE THREAD

**Issue by megamorphg** [rcmaehl/MSEdgeRedirect#77]
**Check List**
- [x] Microsoft Edge is still installed (see #26)
- [x] Running `microsoft-edge:https://google.com` redirects successfully
- [x] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Installed Mode**
- [x] Active Mode
- [ ] Service Mode

**Describe the bug**

**To Reproduce**
1. Launch Edge
2. Get an error:
![image](https://user-images.githubusercontent.com/1782353/154087747-7d1f07d0-c2c7-422b-869d-c85c6983a062.png)

**⚠️ File Upload ⚠️**

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

**Desktop (please complete the following information):**
 - Windows Version: 10 Pro
 - Windows Build: 19043.1466

Context:
I like to use Edge as an alternative browser but not as my default browser.

**Comment by rcmaehl** [comment]
That's a new one. The `Application\Version#\` folder isn't touched at all by MSEdgeRedirect, mainly because I can't be bothered to track versioning each time. Was there any system updates or other changes before this occurred?

**Comment by megamorphg** [comment]
Update: when I switch to Service mode, Edge is able to launch again. So this only occurs when in Active mode.

**Comment by rcmaehl** [comment]
> There's a pending Windows 10 update so maybe there was some system updates. (I need to find a time to restart, I have a lot of apps and tabs open.) When I run the following it redirects to Chrome with the following error: `"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe" --profile-directory=Default`
> 
> ![image](https://user-images.githubusercontent.com/1782353/154096190-521a22a0-cc10-4d2f-84ff-3f011aabca1c.png)

Ah, that should be fixed in 0.6.3.0. I'm finalizing some changes to that.

**Comment by jed84** [comment]
I have MSEdgeRedirect 0.6.4.0 (active mode) installed and I am getting the same error when I try to update MS Edge.

Is there a way to fix it without uninstalling MSEdgeRedirect?

![obraz](https://user-images.githubusercontent.com/47121522/160259814-e3697fa5-3287-42b5-a8c3-276ed3bb440f.png)

**Comment by rcmaehl** [comment]
> I have MSEdgeRedirect 0.6.4.0 (active mode) installed and I am getting the same error when I try to update MS Edge.
> 
> Is there a way to fix it without uninstalling MSEdgeRedirect?
> 
> ![obraz](https://user-images.githubusercontent.com/47121522/160259814-e3697fa5-3287-42b5-a8c3-276ed3bb440f.png)

Run `msedgeredirect.exe /repair` from it's program files directory and then reboot.

**Comment by jed84** [comment]
I am still getting this error after each update of MS Edge.

Am I running the command in the right directory?

![obraz](https://user-images.githubusercontent.com/47121522/162326502-9746bd4e-70ee-4f58-a4de-73d5f675916f.png)

**Comment by rcmaehl** [comment]
> I am still getting this error after each update of MS Edge.
> 
> Am I running the command in the right directory?
> 
> ![obraz](https://user-images.githubusercontent.com/47121522/162326502-9746bd4e-70ee-4f58-a4de-73d5f675916f.png)

Please try the latest dev build, I've greatly improved fixing this

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by jed84** [comment]
Hey @rcmaehl 
This is resolved within the new version linked by you.

Thank you.
